name: Build

on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings -W rust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: 1
      ASOUL_WEEKLY_URL: https://example.com
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenCV
        run: |
          sudo apt-get update
          sudo apt-get install -y libopencv-core-dev libopencv-imgproc-dev libopencv-imgcodecs-dev libclang-dev
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: |
          cargo check   --workspace
          cargo clippy  -- -D warnings 
          cargo test    --workspace
